### ISSUE TITLE
can't install through composer/packagist

### ISSUE THREAD

**Issue by borazslo** [kenguest/Services_Openstreetmap#5]
I put this into my composer.json:
```
"require": {
    	"kenguest/services-openstreetmap": "dev-master"
    }
```
But as my composer tries updating itself, it says: 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kenguest/services-openstreetmap dev-master -> satisfiable by kenguest/services-openstreetmap[dev-master].
    - kenguest/services-openstreetmap dev-master requires pear-pear/http_request2 2.0.0 -> no matching package found.
```

**Comment by FireLizard** [comment]
Same here (with new stable release v0.4.0)!

@borazslo I quess you already solve that? Maybe by downloading the archive.

**Comment by kenguest** [comment]
I'll see what I can do later in the week to get this working properly.

**Comment by kenguest** [comment]
composer require kenguest/services-openstreetmap:dev-master should work now, as I relaxed some of the requirements to more up-to-date versions.

**Comment by FireLizard** [comment]
Works! Thx :)
