### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by FireLizard** [kenguest/Services_Openstreetmap#7]
Hey,
are you planning a new release in the next time?

I see your [last release](https://github.com/kenguest/Services_Openstreetmap/commit/1fe91fdaf6f301d3ba31103ad5aefcf20eca1a8a) was on 18. Dec '13.

Greetings

**Comment by kenguest** [comment]
Thanks for the nudge @FireLizard!

I'll release the current work done since then until now later this week.

**Comment by kenguest** [comment]
I've just issued a new release - v0.4.0 :-)

**Comment by FireLizard** [comment]
Yeah, pretty cool^^
Thank you!

**Comment by Firefishy** [comment]
<3

**Comment by Firefishy** [comment]
❤
